


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."lead_status" AS ENUM (
    'NUEVO',
    'CONTACTADO',
    'VISITA PROGRAMADA',
    'NEGOCIACIÓN',
    'CERRADO',
    'DESCARTADO'
);


ALTER TYPE "public"."lead_status" OWNER TO "postgres";


CREATE TYPE "public"."property_status" AS ENUM (
    'EN_VENTA',
    'EN_ALQUILER',
    'RESERVADO',
    'VENDIDO',
    'ALQUILADO'
);


ALTER TYPE "public"."property_status" OWNER TO "postgres";


CREATE TYPE "public"."property_type" AS ENUM (
    'CASA',
    'DEPARTAMENTO',
    'PH',
    'TERRENO',
    'LOCAL COMERCIAL',
    'OFICINA COMERCIAL',
    'CAMPO',
    'GARAGE',
    'FONDO DE COMERCIO',
    'CONSULTORIO',
    'OTRO'
);


ALTER TYPE "public"."property_type" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."increment_views"("property_id" "uuid") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  UPDATE public.properties
  SET views_count = views_count + 1
  WHERE id = property_id;
END;
$$;


ALTER FUNCTION "public"."increment_views"("property_id" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_all_normalized_prices"("new_rate" numeric) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  -- Primero, actualiza las propiedades en ARS (precio 1 a 1)
  UPDATE public.properties
  SET price_normalized_ars = price
  WHERE currency = 'ARS';

  -- Segundo, actualiza las propiedades en USD (precio * nueva tasa)
  UPDATE public.properties
  SET price_normalized_ars = price * new_rate
  WHERE currency = 'USD';
END;
$$;


ALTER FUNCTION "public"."update_all_normalized_prices"("new_rate" numeric) OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."agents" (
    "id" "uuid" NOT NULL,
    "full_name" "text",
    "phone" "text",
    "email" "text",
    "avatar_url" "text",
    "role" "text" DEFAULT 'agente'::"text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."agents" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."amenities" (
    "id" bigint NOT NULL,
    "name" "text",
    "icon_name" "text"
);


ALTER TABLE "public"."amenities" OWNER TO "postgres";


ALTER TABLE "public"."amenities" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."amenities_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."events" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "date" timestamp with time zone NOT NULL,
    "title" "text" NOT NULL,
    "time" "text" NOT NULL,
    "agent_id" "uuid" DEFAULT "auth"."uid"()
);


ALTER TABLE "public"."events" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."exchange_rates" (
    "id" integer NOT NULL,
    "usd_to_ars" numeric
);


ALTER TABLE "public"."exchange_rates" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."lead_notes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "content" "text",
    "lead_id" "uuid",
    "user_id" "uuid"
);


ALTER TABLE "public"."lead_notes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."leads" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "email" "text",
    "phone" "text",
    "status" "public"."lead_status",
    "source" "text",
    "notes" "text",
    "property_id" "uuid",
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "agent_id" "uuid",
    "created_by" "uuid" DEFAULT "auth"."uid"()
);


ALTER TABLE "public"."leads" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."notifications" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "title" "text" NOT NULL,
    "message" "text" NOT NULL,
    "is_read" boolean DEFAULT false NOT NULL,
    "link" "text",
    "type" "text" DEFAULT 'info'::"text"
);


ALTER TABLE "public"."notifications" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."properties" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "street_address" "text",
    "price" numeric,
    "currency" "text",
    "operation_type" "text",
    "property_type_id" bigint,
    "bedrooms" smallint,
    "bathrooms" smallint,
    "total_area" numeric,
    "covered_area" numeric,
    "status" "public"."property_status" NOT NULL,
    "agent_id" "uuid" DEFAULT "gen_random_uuid"(),
    "latitude" numeric,
    "longitude" numeric,
    "neighborhood" "text",
    "city" "text",
    "province" "text",
    "rooms" smallint,
    "expensas" smallint,
    "antiguedad" "text",
    "cocheras" "text",
    "price_normalized_ars" numeric,
    "views_count" integer DEFAULT 0
);


ALTER TABLE "public"."properties" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."property_amenities" (
    "property_id" "uuid" NOT NULL,
    "amenity_id" bigint NOT NULL
);


ALTER TABLE "public"."property_amenities" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."property_images" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "property_id" "uuid" DEFAULT "gen_random_uuid"(),
    "image_url" "text",
    "order" smallint
);


ALTER TABLE "public"."property_images" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."property_types" (
    "id" bigint NOT NULL,
    "name" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."property_types" OWNER TO "postgres";


ALTER TABLE "public"."property_types" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."property_types_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."agents"
    ADD CONSTRAINT "agents_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."amenities"
    ADD CONSTRAINT "amenities_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."exchange_rates"
    ADD CONSTRAINT "exchange_rates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."lead_notes"
    ADD CONSTRAINT "lead_notes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."properties"
    ADD CONSTRAINT "properties_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."property_amenities"
    ADD CONSTRAINT "property_amenities_pkey" PRIMARY KEY ("property_id", "amenity_id");



ALTER TABLE ONLY "public"."property_images"
    ADD CONSTRAINT "property_images_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."property_types"
    ADD CONSTRAINT "property_types_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_properties_price_normalized_ars" ON "public"."properties" USING "btree" ("price_normalized_ars");



ALTER TABLE ONLY "public"."agents"
    ADD CONSTRAINT "agents_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."lead_notes"
    ADD CONSTRAINT "lead_notes_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "public"."leads"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."lead_notes"
    ADD CONSTRAINT "lead_notes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_agent_id_fkey" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id");



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."properties"
    ADD CONSTRAINT "properties_agent_id_fkey" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id");



ALTER TABLE ONLY "public"."properties"
    ADD CONSTRAINT "properties_property_type_id_fkey" FOREIGN KEY ("property_type_id") REFERENCES "public"."property_types"("id");



ALTER TABLE ONLY "public"."property_amenities"
    ADD CONSTRAINT "property_amenities_amenity_id_fkey" FOREIGN KEY ("amenity_id") REFERENCES "public"."amenities"("id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."property_amenities"
    ADD CONSTRAINT "property_amenities_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."property_images"
    ADD CONSTRAINT "property_images_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON UPDATE CASCADE;



CREATE POLICY "Actualizar propias notificaciones" ON "public"."notifications" FOR UPDATE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Admins pueden ver todos los leads" ON "public"."leads" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."agents"
  WHERE (("agents"."id" = "auth"."uid"()) AND ("agents"."role" = 'admin'::"text")))));



CREATE POLICY "Admins ven todas las notas" ON "public"."lead_notes" TO "authenticated" USING ((( SELECT "agents"."role"
   FROM "public"."agents"
  WHERE ("agents"."id" = "auth"."uid"())) = 'admin'::"text"));



CREATE POLICY "Agentes crean notas en sus leads" ON "public"."lead_notes" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."leads"
  WHERE (("leads"."id" = "lead_notes"."lead_id") AND ("leads"."agent_id" = "auth"."uid"())))));



CREATE POLICY "Agentes ven notas de sus leads" ON "public"."lead_notes" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."leads"
  WHERE (("leads"."id" = "lead_notes"."lead_id") AND ("leads"."agent_id" = "auth"."uid"())))));



CREATE POLICY "Agentes ven sus propios leads" ON "public"."leads" TO "authenticated" USING ((("agent_id" = "auth"."uid"()) OR ("created_by" = "auth"."uid"())));



CREATE POLICY "Agents can delete their own properties" ON "public"."properties" FOR DELETE USING (( SELECT ("auth"."uid"() = "properties"."agent_id")));



CREATE POLICY "Agents can insert images for their own properties" ON "public"."property_images" FOR INSERT WITH CHECK (("auth"."uid"() IN ( SELECT "properties"."agent_id"
   FROM "public"."properties"
  WHERE ("properties"."id" = "property_images"."property_id"))));



CREATE POLICY "Agents can manage notes for their own leads" ON "public"."lead_notes" USING ((("auth"."uid"() = "user_id") AND (EXISTS ( SELECT 1
   FROM "public"."leads"
  WHERE (("leads"."id" = "lead_notes"."lead_id") AND ("leads"."user_id" = "auth"."uid"()))))));



CREATE POLICY "Agents can update their own properties" ON "public"."properties" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "agent_id")) WITH CHECK (("auth"."uid"() = "agent_id"));



CREATE POLICY "Borrar propios eventos" ON "public"."events" FOR DELETE USING (("auth"."uid"() = "agent_id"));



CREATE POLICY "Borrar: Dueño o Admin" ON "public"."properties" FOR DELETE TO "authenticated" USING ((("agent_id" = "auth"."uid"()) OR (( SELECT "agents"."role"
   FROM "public"."agents"
  WHERE ("agents"."id" = "auth"."uid"())) = 'admin'::"text")));



CREATE POLICY "Crear propios eventos" ON "public"."events" FOR INSERT WITH CHECK (("auth"."uid"() = "agent_id"));



CREATE POLICY "Cualquiera puede ver agentes" ON "public"."agents" FOR SELECT USING (true);



CREATE POLICY "Editar: Dueño o Admin" ON "public"."properties" FOR UPDATE TO "authenticated" USING ((("agent_id" = "auth"."uid"()) OR (( SELECT "agents"."role"
   FROM "public"."agents"
  WHERE ("agents"."id" = "auth"."uid"())) = 'admin'::"text")));



CREATE POLICY "Enable delete for users based on user_id" ON "public"."agents" FOR DELETE TO "authenticated" USING ((( SELECT "agents_1"."role"
   FROM "public"."agents" "agents_1"
  WHERE ("agents_1"."id" = "auth"."uid"())) = 'admin'::"text"));



CREATE POLICY "Enable delete for users based on user_id" ON "public"."property_amenities" FOR DELETE USING (("auth"."uid"() IN ( SELECT "properties"."agent_id"
   FROM "public"."properties"
  WHERE ("properties"."id" = "property_amenities"."property_id"))));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."amenities" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."leads" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."property_amenities" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."property_types" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."agents" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."amenities" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."leads" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."properties" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."property_amenities" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."property_images" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."property_types" FOR SELECT USING (true);



CREATE POLICY "Insertar propias notificaciones (Sistema)" ON "public"."notifications" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Usuarios pueden crear propiedades" ON "public"."properties" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "agent_id"));



CREATE POLICY "Usuarios ven todas las propiedades" ON "public"."properties" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Ver propias notificaciones" ON "public"."notifications" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Ver propios eventos" ON "public"."events" FOR SELECT USING (("auth"."uid"() = "agent_id"));



ALTER TABLE "public"."agents" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."amenities" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."lead_notes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."leads" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."properties" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."property_amenities" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."property_images" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."property_types" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."increment_views"("property_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."increment_views"("property_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."increment_views"("property_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."update_all_normalized_prices"("new_rate" numeric) TO "anon";
GRANT ALL ON FUNCTION "public"."update_all_normalized_prices"("new_rate" numeric) TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_all_normalized_prices"("new_rate" numeric) TO "service_role";


















GRANT ALL ON TABLE "public"."agents" TO "anon";
GRANT ALL ON TABLE "public"."agents" TO "authenticated";
GRANT ALL ON TABLE "public"."agents" TO "service_role";



GRANT ALL ON TABLE "public"."amenities" TO "anon";
GRANT ALL ON TABLE "public"."amenities" TO "authenticated";
GRANT ALL ON TABLE "public"."amenities" TO "service_role";



GRANT ALL ON SEQUENCE "public"."amenities_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."amenities_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."amenities_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."events" TO "anon";
GRANT ALL ON TABLE "public"."events" TO "authenticated";
GRANT ALL ON TABLE "public"."events" TO "service_role";



GRANT ALL ON TABLE "public"."exchange_rates" TO "anon";
GRANT ALL ON TABLE "public"."exchange_rates" TO "authenticated";
GRANT ALL ON TABLE "public"."exchange_rates" TO "service_role";



GRANT ALL ON TABLE "public"."lead_notes" TO "anon";
GRANT ALL ON TABLE "public"."lead_notes" TO "authenticated";
GRANT ALL ON TABLE "public"."lead_notes" TO "service_role";



GRANT ALL ON TABLE "public"."leads" TO "anon";
GRANT ALL ON TABLE "public"."leads" TO "authenticated";
GRANT ALL ON TABLE "public"."leads" TO "service_role";



GRANT ALL ON TABLE "public"."notifications" TO "anon";
GRANT ALL ON TABLE "public"."notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."notifications" TO "service_role";



GRANT ALL ON TABLE "public"."properties" TO "anon";
GRANT ALL ON TABLE "public"."properties" TO "authenticated";
GRANT ALL ON TABLE "public"."properties" TO "service_role";



GRANT ALL ON TABLE "public"."property_amenities" TO "anon";
GRANT ALL ON TABLE "public"."property_amenities" TO "authenticated";
GRANT ALL ON TABLE "public"."property_amenities" TO "service_role";



GRANT ALL ON TABLE "public"."property_images" TO "anon";
GRANT ALL ON TABLE "public"."property_images" TO "authenticated";
GRANT ALL ON TABLE "public"."property_images" TO "service_role";



GRANT ALL ON TABLE "public"."property_types" TO "anon";
GRANT ALL ON TABLE "public"."property_types" TO "authenticated";
GRANT ALL ON TABLE "public"."property_types" TO "service_role";



GRANT ALL ON SEQUENCE "public"."property_types_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."property_types_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."property_types_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

drop policy "Enable delete for users based on user_id" on "public"."agents";

drop policy "Admins ven todas las notas" on "public"."lead_notes";

drop policy "Agentes crean notas en sus leads" on "public"."lead_notes";

drop policy "Agentes ven notas de sus leads" on "public"."lead_notes";

drop policy "Agents can manage notes for their own leads" on "public"."lead_notes";

drop policy "Admins pueden ver todos los leads" on "public"."leads";

drop policy "Borrar: Dueño o Admin" on "public"."properties";

drop policy "Editar: Dueño o Admin" on "public"."properties";

drop policy "Enable delete for users based on user_id" on "public"."property_amenities";

drop policy "Agents can insert images for their own properties" on "public"."property_images";

alter table "public"."lead_notes" drop constraint "lead_notes_lead_id_fkey";

alter table "public"."leads" drop constraint "leads_agent_id_fkey";

alter table "public"."leads" drop constraint "leads_property_id_fkey";

alter table "public"."properties" drop constraint "properties_agent_id_fkey";

alter table "public"."properties" drop constraint "properties_property_type_id_fkey";

alter table "public"."property_amenities" drop constraint "property_amenities_amenity_id_fkey";

alter table "public"."property_amenities" drop constraint "property_amenities_property_id_fkey";

alter table "public"."property_images" drop constraint "property_images_property_id_fkey";

alter table "public"."leads" alter column "status" set data type public.lead_status using "status"::text::public.lead_status;

alter table "public"."properties" alter column "status" set data type public.property_status using "status"::text::public.property_status;

alter table "public"."lead_notes" add constraint "lead_notes_lead_id_fkey" FOREIGN KEY (lead_id) REFERENCES public.leads(id) ON DELETE CASCADE not valid;

alter table "public"."lead_notes" validate constraint "lead_notes_lead_id_fkey";

alter table "public"."leads" add constraint "leads_agent_id_fkey" FOREIGN KEY (agent_id) REFERENCES public.agents(id) not valid;

alter table "public"."leads" validate constraint "leads_agent_id_fkey";

alter table "public"."leads" add constraint "leads_property_id_fkey" FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE SET NULL not valid;

alter table "public"."leads" validate constraint "leads_property_id_fkey";

alter table "public"."properties" add constraint "properties_agent_id_fkey" FOREIGN KEY (agent_id) REFERENCES public.agents(id) not valid;

alter table "public"."properties" validate constraint "properties_agent_id_fkey";

alter table "public"."properties" add constraint "properties_property_type_id_fkey" FOREIGN KEY (property_type_id) REFERENCES public.property_types(id) not valid;

alter table "public"."properties" validate constraint "properties_property_type_id_fkey";

alter table "public"."property_amenities" add constraint "property_amenities_amenity_id_fkey" FOREIGN KEY (amenity_id) REFERENCES public.amenities(id) ON UPDATE CASCADE not valid;

alter table "public"."property_amenities" validate constraint "property_amenities_amenity_id_fkey";

alter table "public"."property_amenities" add constraint "property_amenities_property_id_fkey" FOREIGN KEY (property_id) REFERENCES public.properties(id) ON UPDATE CASCADE not valid;

alter table "public"."property_amenities" validate constraint "property_amenities_property_id_fkey";

alter table "public"."property_images" add constraint "property_images_property_id_fkey" FOREIGN KEY (property_id) REFERENCES public.properties(id) ON UPDATE CASCADE not valid;

alter table "public"."property_images" validate constraint "property_images_property_id_fkey";


  create policy "Enable delete for users based on user_id"
  on "public"."agents"
  as permissive
  for delete
  to authenticated
using ((( SELECT agents_1.role
   FROM public.agents agents_1
  WHERE (agents_1.id = auth.uid())) = 'admin'::text));



  create policy "Admins ven todas las notas"
  on "public"."lead_notes"
  as permissive
  for all
  to authenticated
using ((( SELECT agents.role
   FROM public.agents
  WHERE (agents.id = auth.uid())) = 'admin'::text));



  create policy "Agentes crean notas en sus leads"
  on "public"."lead_notes"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.leads
  WHERE ((leads.id = lead_notes.lead_id) AND (leads.agent_id = auth.uid())))));



  create policy "Agentes ven notas de sus leads"
  on "public"."lead_notes"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.leads
  WHERE ((leads.id = lead_notes.lead_id) AND (leads.agent_id = auth.uid())))));



  create policy "Agents can manage notes for their own leads"
  on "public"."lead_notes"
  as permissive
  for all
  to public
using (((auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM public.leads
  WHERE ((leads.id = lead_notes.lead_id) AND (leads.user_id = auth.uid()))))));



  create policy "Admins pueden ver todos los leads"
  on "public"."leads"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.agents
  WHERE ((agents.id = auth.uid()) AND (agents.role = 'admin'::text)))));



  create policy "Borrar: Dueño o Admin"
  on "public"."properties"
  as permissive
  for delete
  to authenticated
using (((agent_id = auth.uid()) OR (( SELECT agents.role
   FROM public.agents
  WHERE (agents.id = auth.uid())) = 'admin'::text)));



  create policy "Editar: Dueño o Admin"
  on "public"."properties"
  as permissive
  for update
  to authenticated
using (((agent_id = auth.uid()) OR (( SELECT agents.role
   FROM public.agents
  WHERE (agents.id = auth.uid())) = 'admin'::text)));



  create policy "Enable delete for users based on user_id"
  on "public"."property_amenities"
  as permissive
  for delete
  to public
using ((auth.uid() IN ( SELECT properties.agent_id
   FROM public.properties
  WHERE (properties.id = property_amenities.property_id))));



  create policy "Agents can insert images for their own properties"
  on "public"."property_images"
  as permissive
  for insert
  to public
with check ((auth.uid() IN ( SELECT properties.agent_id
   FROM public.properties
  WHERE (properties.id = property_images.property_id))));



  create policy "Give users access to own folder 1jpriur_0"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'properties'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "Give users access to own folder 1jpriur_1"
  on "storage"."objects"
  as permissive
  for update
  to public
using (((bucket_id = 'properties'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "Give users access to own folder 1jpriur_2"
  on "storage"."objects"
  as permissive
  for delete
  to public
using (((bucket_id = 'properties'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "avatarimage 1oj01fe_0"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'avatars'::text));



  create policy "avatarimage 1oj01fe_1"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'avatars'::text));



  create policy "avatarimage 1oj01fe_2"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using ((bucket_id = 'avatars'::text));



  create policy "avatarimage 1oj01fe_3"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using ((bucket_id = 'avatars'::text));



